name: Plugin Check
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          coverage: none
          tools: wp-cli
      - run: composer install --no-dev --ignore-platform-reqs --optimize-autoloader

      - name: Assets build
        run: |
          npm install
          npm run build

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          wp dist-archive . /tmp/plugin.tar.gz --format=targz
          mkdir /tmp/tmp-build
          tar --extract --file=/tmp/plugin.tar.gz --strip-components=1 --directory=/tmp/tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './tmp-build/plugin'
