name: Plugin Check
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          coverage: none
          tools: wp-cli
      - run: composer install --no-dev --ignore-platform-reqs --optimize-autoloader

      - name: Assets build
        run: |
          npm install
          npm run build

      - name: Build plugin
        run: |
          wp dist-archive . ./plugin.zip
          mkdir tmp-build
          unzip plugin.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './tmp-build/plugin'
